services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "sql10452375"
      MYSQL_USER: "sql10452375"
      MYSQL_PASSWORD: "5882z5CSVK"
      MYSQL_ROOT_PASSWORD: "5882z5CSVK"

    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3306
