-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema musiqueirosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musiqueirosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musiqueirosdb` DEFAULT CHARACTER SET utf8 ;
USE `musiqueirosdb` ;

-- -----------------------------------------------------
-- Table `musiqueirosdb`.`usersDB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiqueirosdb`.`usersDB` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(12) NULL,
  `apellido` VARCHAR(10) NULL,
  `password` VARCHAR(50) NULL,
  `email` VARCHAR(20) NULL,
  `userAvatar` VARCHAR(20) NULL,
  `bio` VARCHAR(45) NULL,
  `usersDBcol` VARCHAR(141) NULL,
  `skills` VARCHAR(40) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musiqueirosdb`.`songsDB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiqueirosdb`.`songsDB` (
  `songId` INT NULL AUTO_INCREMENT,
  `img` VARCHAR(20) NULL,
  `titulo` VARCHAR(25) NULL,
  `precioUnitario` INT NULL,
  `descripcion` VARCHAR(80) NULL,
  `audioFileYTPlayer` VARCHAR(15) NULL,
  `audioFile` VARCHAR(70) NULL,
  `tipoProducto` VARCHAR(20) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`songId`),
  INDEX `fkSongsDBUsersDB1idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fkSongsDBUsersDB1`
    FOREIGN KEY (`id`)
    REFERENCES `musiqueirosdb`.`usersDB` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musiqueirosdb`.`instrumentsDB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiqueirosdb`.`instrumentsDB` (
  `instrumId` INT NULL AUTO_INCREMENT,
  `img` VARCHAR(20) NULL,
  `titulo` VARCHAR(60) NULL,
  `descripcion` VARCHAR(420) NULL,
  `precioUnitario` INT NULL,
  `tipoProducto` VARCHAR(20) NULL,
  `id` INT NULL,
  PRIMARY KEY (`instrumId`),
  INDEX `fkInstrumentsDBUsersDB1_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fkInstrumentsDBUsersDB1`
    FOREIGN KEY (`id`)
    REFERENCES `musiqueirosdb`.`usersDB` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Import Data
-- -----------------------------------------------------


INSERT INTO usersDB VALUES
    (1,'Aaron','Kenny','B0?;NV','Aaron.Kenny@gmail.com','07.jpg',3,'Vivo en Rosario. Tengo influencias del jazz de Miles Davis. 34 años','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\07','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\'),
    (2,'Nate','Parrish','JF;XMH','Nate.Parrish@gmail.com','05.jpg',4,'Influencias de RHCP y de RATM. Vivo en Nueva York pero mantengo mis raices Argentinas ;-)','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\05',NULL),
    (3,'Bad','Snacks','S0=ORD','Bad.Snacks@gmail.com','01.jpg',4,'Toco la guitarra y canto. Me gusta el rock y el trap','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\01',NULL),
    (4,'Cheel',NULL,'?OFX3Y','Cheel@gmail.com','02.jpg',5,'Vivo en Chubut. Estoy disponible para crear bandas','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\02',NULL),
    (5,'Chris','Haugen','=C3LBN','Chris.Haugen@gmail.com','06.jpg',1,'Nerd musical. Mis influencias son tan variadas que van desde la clasica hasta el rock fusion','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\06',NULL),
    (6,'Corbyn','Kites','<>GW94','Corbyn.Kites@yahoo.com','03.jpg',5,'Somos una banda de Avellaneda. Nos influencia la musica urbana. Tocamos desde hace 10 años','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\03',NULL),
    (7,'Jamelle','Monae','KSI6;1','Jamelle.Monae@gmail.com','08.jpg',3,'Me encanta Bork. Actualmente estoy sin banda por lo que estoy disponible para cantar en una','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\08',NULL),
    (8,'Timothy','Hansen','ZHWDEX','Timothy.Hansen@gmail.com','09.jpg',4,'Mis influencias son Jamie Collum. Mi genero musical preferido es el jazz contemporaneo','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\09',NULL),
    (9,'Delicate','Steve','5U3WBJ','Delicate.Steve@gmail.com','48.jpg',3,'Tengo una voz suave y armoniosa. Mi preferencia son las melodias y las baladas romanticas','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\',NULL),
    (10,'Replacements',NULL,'UF6I0Y','Replacements@gmail.com','04.jpg',1,'Creamos Replacements porque somos amigos del barrio de Boedo. Hinchas de San Lorenzo y amantes del rock','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\04',NULL),
    (11,'Outside In',NULL,':K4;WV','Outside In@gmail.com','11.jpg',2,'Outside in es una banda de Mar del Plata con influencias reggae. Estamos disponibles para shows','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\11',NULL),
    (12,'Emmit','Fenn','V=6P>M','Emmit.Fenn@yahoo.com','10.jpg',4,'Soy Americano pero vivo en Buenos Aires desde los 14 años. Me influencia Radiohead y Pulp','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\10',NULL),
    (13,'E''s','Jammy Jams','<SXSP@','E''s.Jammy Jams@gmail.com','13.jpg',5,'Amante de la musica electronica. Geek de sintetizadores y guitarras electricas','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\13',NULL),
    (14,'Aillike','Leddy','UNY6UL','Aillike.Leddy@gmail.com','19.jpg',1,'Duo de musica electronica, versatiles en todos los generos musicales.','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\19',NULL),
    (15,'Godmode',NULL,'JSFASP','Godmode@gmail.com','14.jpg',1,'Trio trio creado en La Plata. Hacemos rock hasta llegar a los cimientos de la tierra','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\14',NULL),
    (16,'Jeremy','Korpas','4>=@O<','Jeremy.Korpas@yahoo.com','12.jpg',4,'Mis estilos preferidos son el Pop y el Rock, y logro combinaciones exquisitas con ellos','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\12',NULL),
    (17,'JHS','Pedals','UKHP;G','JHS.Pedals@gmail.com','15.jpg',2,'Me especializo en ponerle ritmo a las melodias. Soy Baterista y percusionista','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\15',NULL),
    (18,'Joel','Cummins','9P0?O@','Joel.Cummins@yahoo.com','16.jpg',4,'5 discos editados y 5 canciones en el Billboard chart. Toque en el Quilmes Rock','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\16',NULL),
    (19,'Lauren','Duski','LSE?ZK','Lauren.Duski@gmail.com','21.jpg',3,'Me gusta conocer los misterios de la voz y desentranarlos. Soy cantante desde que tengo memoria','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\21',NULL),
    (20,'Travis','Scott','TNBVG9','Travis.Scott@gmail.com','17.jpg',4,'Soy guitarrista, compositor y cantante. Me gustan bandas tipo Kings of Lions','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\17',NULL),
    (21,'Glass','Animals','YSG3LA','Glass.Animals@gmail.com','18.jpg',4,'Hacemos power rock para despertar conciencias.','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\18',NULL),
    (22,'Nathan','Moore','TRG?<Z','Nathan.Moore@yahoo.com','20.jpg',4,'Soy introvertido y me gusta crear mis composiciones en mi home studio. 30 años','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\20',NULL),
    (23,'Ofshane',NULL,'DSHL<@','Ofshane@gmail.com','22.jpg',1,'Estamos disponibles para shows y eventos empresariales. 3 discos editados. Influencias Magic Numbers','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\22',NULL),
    (24,'Patiño',NULL,'?=@BWR','Patiño@yahoo.com','23.jpg',3,'Soy Zenegales. Vivo en Argentina desde hace 5 años. Disponible para bandas','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\23',NULL),
    (25,'Quincas','Moreira','27TGQ8','Quincas.Moreira@gmail.com','25.jpg',3,'Admiro a los cantantes de musica folk y country. Vivo en Arkansas','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\25',NULL),
    (26,'RAGE',NULL,'TVBHXI','RAGE@gmail.com','26.jpg',2,'Somos una banda de Hurlingham. Nuestras influencias son bandas nacionales como Seru Giran y Pescado Rabioso. Tocamos juntos desde hace 5 años','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\26',NULL),
    (27,'Reed','Mathis','XHD4TR','Reed.Mathis@yahoo.com','24.jpg',4,'Vivo en la ciduad de Sao Paulo. Soy brasileño y me influencia el funk clasico','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\24',NULL),
    (28,'Robotanists',NULL,'FZN<YU','Robotanists@gmail.com','27.jpg',2,'Somos un duo de Drum and Bass. Nuestras influencias son claro, la mejor banda de todos los tiempos Morphine','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\27',NULL),
    (29,'SefChol',NULL,'O41BWP','SefChol@gmail.com','29.jpg',3,'Banda de sonidos eclecticos y originales. Nos encanta la musica y poder fusionarla','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\29',NULL),
    (30,'Kid','Head','Q;T<I:','Kid.Head@yahoo.com','30.jpg',1,'Tenemos influencias en el rock californiano. Combinamos la musica con el skate.','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\30',NULL),
    (31,'Steve','Adams','8LHR2M','Steve.Adams@gmail.com','28.jpg',4,'Solista y 5. Mi pasion es componer. La musica cambia al mundo','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\28',NULL),
    (32,'Air','Review','ATWBFM','Air.Review@gmail.com','32.jpg',3,'Banda relajada de Rock and roll clasico, influenciados por Led Zeppellin y Black Sabbath','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\32',NULL),
    (33,'Roosevelt','Sea','5IB6T@','Roosevelt.Sea@gmail.com','34.jpg',3,'Luego de haber pasado por varias bandas, inicie mi carrera solista y lance tres discos hasta el momento','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\34',NULL),
    (34,'Dave','Fields','4UQ64Y','Dave.Fields@yahoo.com','36.jpg',4,'Observo el mundo desde mi estudio y escribo acerca de el, en tonos de rock sinfonico','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\36',NULL),
    (35,'Chloe','Morondo','S0P10P','Chloe.Morondo@gmail.com','31.jpg',3,'Soy Mezzosoprano. Cantante de opera profesional','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\31',NULL),
    (36,'TrackTribe',NULL,'XOJ192','TrackTribe@gmail.com','37.jpg',3,'Estamos disponibles para shows y eventos empresariales. 2 discos editados. Influencias de grupos rhythm and blues','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\37',NULL),
    (37,'Trevor','Garrod','<22MC2','Trevor.Garrod@gmail.com','40.jpg',3,'Canto y compongo mis propias canciones, siendo influenciado por los clasicos del soul','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\40',NULL),
    (38,'Back 2 zero',NULL,'<QEUQ>','Back 2 zero@yahoo.com','35.jpg',3,'Banda liderada por la cantante Julia Nono. Hacemos Jazz vocal y shows tributo','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\35',NULL),
    (39,'Hallmarc',NULL,'CBR00D','Hallmarc@gmail.com','39.jpg',3,'Soy Morena Lopez. Nuestras influencias van desde el flamenco hasta la electronica','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\39',NULL),
    (40,'Vans','in Japan','H6ADHO','Vans.in Japan@gmail.com','33.jpg',3,'Lidero la banda Vans in Japan. Nos gusta experimentar y crear nuevas variantes de los clasicos generos musicales','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\33',NULL),
    (41,'Parks','Square','?AIVTU','Parks.Square@yahoo.com','38.jpg',4,'Trio que recrea los clasicos del rock nacional. Banda Tributo a los clasicos nacionales','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\38',NULL),
    (42,'Zachariah','Hickman','BK8MU2','Zachariah.Hickman@gmail.com','44.jpg',6,'Banda reggae de la zona oeste del gran Buenos Aires. 3 discos editados','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\usersAvatars\\resizedandcropped\\44',NULL);



INSERT INTO InstrumentsDB VALUES
    (1,1,'01.jpg','Bajo Electrico Acustico Femmto Precision','CARACTERISTICAS - Formato de guitarra simil Jazz Bass, para diestros, pasivo - Madera cuerpo: Aliso - Madera mástil: Arce - Diapasón: Palisandro - Clavijas forma trébol, 4L, de fundición cromadas - Cuerdas de metal - microfono bobina partida (split coil, tipo Precision Bass) - 2 perillas (volumen y tono) - 21 trastes - Pick guard
- Salida: Jack plug 6.5mm',42,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\01.jpg'),
    (2,2,'02.jpg','Bajo Electrico Fender Jaguar Bass 4 Cuerdas','Producto: Bajo Electrico
Marca: Fender
Modelo: Jaguar Bass Caracteristicas: Bajo Electrico Fender Jaguar Bass 4 Cuerdas Perfecto Estado.',333,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\02.jpg'),
    (3,3,'03.jpg','Bajo Electrico 4 Cuedras Con Ampli Y Afinador','Bajo usado en buen estado no se la marca',36,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\03.jpg'),
    (4,4,'04.jpg','Bajo Eléctrico Guild - Década Del 90 Impecable - Gran Sonido','Como nuevo. Hecho en Argentina. Década de 1980 a 1990. Impecable',140,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\04.jpg'),
    (5,5,'05.jpg','Bajo Electrico Texas','Bajo eléctrico de 4 cuerdas tipo Ibanez, de circuito Activo. Dos mics unos tipo jazz bass y el otro precision bass. Dos perillas de tonos, dos perillas de volumen. Color Tobacoo Burst. Solo de poco uso doméstico. Buen sonido. Calibrado con cuerdas nuevas Martin Blust de .40. Se entrega con funda de bajo acolchonada y una pua rigida. Zona Ezeiza para probarlo o entrega en todo el Conurbano Bonaerense previo acuerdo.',134,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\05.jpg'),
    (6,6,'06.jpg','Bajo Electrico Tipo Fender Tyler','Exelente bajo tipo fender tyler vintage series jazz bass, exelente estado se lo compre a la persona q lo compro nuevo y no lo uso yo lo use muy copo, lindo sonido con funda',37,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\06.jpg'),
    (7,7,'07.jpg','Bajo Eléctrico Corvette Rock Bass By Warwick 5 Cuerdas Local','SE RETIRA POR EL CENTRO DE LOMAS DE ZAMORA O ENVIO POR MERCADO ENVIO. LOCAL A LA CALLE',27,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\07.jpg'),
    (8,8,'08.jpg','Bajo Electrico Ibanez Gio Gsr 200','Poco uso, solo para maquetear en casa y algún ensayo.
Detalles que pueden verse en las fotos.
La tapa de la batería engancha de un solo lado y del otro lo sostengo con cinta, no afecta al uso ni se cae la batería.
Anda 10 puntos pero busco algún bajo PASIVO ya que soy guitarrista y me resulta más practico para maquetear, no preciso la ganancia de un bajo activo.',330,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\08.jpg'),
    (9,9,'09.jpg','Bajo Eléctrico Dean Hillsboro Blue Activo Jazz Bass','Los bajos de Dean Hillsboro tienen un aspecto retro y un cabezal clásico. Diseñados para jazz, funk y rock, estos instrumentos son ideales para músicos con poco presupuesto que buscan algo un poco diferente.',181,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\09.jpg'),
    (10,10,'10.jpg','Bajo Electrico 5 Cuerdas Ibanez Btb 775 Pb/indonesia','Ibanez BTB five string with Poplar Burl top, Maple neck and Mahogany body.  MK-2 Pickups . 35" scale. 1.85" at nut.  Neck through. Has been played but still in mint condition. Includes cool Hanewinckel padded Gigbag.  Really nice playing fiver with typical Ibanez quality.   Always wanted to try one of these and it didn''t disappoint but I just got an Alembic five string so I can let this go. Ver detalle de la foto.',329,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\10.jpg'),
    (11,11,'11.jpg','Bateria Acústica 5 Cpos Platos Fierros','BATERIA STAR 5 CUERPOS CON FIERROS Y SIN PALILLOS -Tom 12" -Tom 13" -Redoblante 14" -Chancha 16" -Soportes y pedal para Hihat -Soporte recto para Crash.',151,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\11.jpg'),
    (12,12,'12.jpg','Bateria De 5 Cuerpos + Banqueta Y Platillos Natal Dna Gris','La batería NATAL DNA viene completa, con hardware, platillos, pedal para el bombo, butaca e incluso baquetas; todo lo que necesitas para tocar la batería directamente de la caja.',331,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\12.jpg'),
    (13,13,'13.jpg','Bateria Pearl 5 C Export Exx725 22/10/12/16/14x5 Blanco Mate','BATERÍA PEARL Export - 5 Cuerpos - B22"x18 | TT10"x7 | TT12"x8 | TF16"x16 | R14"x5 - Poplar-Mahogany- Jet Black - Sin Fierros',91,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\13.jpg'),
    (14,14,'14.jpg','Batería Acústica Taurus Jazz Maple 4 Cpos Tambo 14 Bombo 18','Batería 4 cuerpos Maple Tom tom 12" x 10" Tom de pie 14" x 16" Bombo 18" x 18" Tambor 14 Rims Flotantes Bombo con 8 torres AROS DE MADERA
Tom holder t/YAMAHA Patas telescópicas Fierros Dobles Soporte Recto Platillo pata doble Soporte HH con regulación pata doble Pedal de bombo cadena doble plataforma de acero
Soporte de redoblante pata doble',14,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\14.jpg'),
    (16,16,'16.jpg','Bateria Mapex Mars Fusion Bombo De 20 Bloodwood Cuotas','Bombo 20"x16" sin soporte para Tom. Tom Tom 10"x07" y 12"x08" Tom Base 14"x12" Caja 14"x6,5 Mars Incluye Soporte doble de tom TH676 No incluye herrajes ni platos ',265,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\16.jpg'),
    (17,17,'17.jpg','Bateria Acustica Completa 5 Cuerpos Platos Fierros','Excelente batería MAPEX PRODIGY, con acabado recubierto, los tambores están equipados con Prodigy, el nuevo modelo que utiliza un solo punto de contacto.
Incluye TODO lo que precisas para tocar',115,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\17.jpg'),
    (20,20,'20.jpg','Bateria Mapex Prodigy Completa','Excelente batería MAPEX PRODIGY, con acabado recubierto, los tambores están equipados con Prodigy, el nuevo modelo que utiliza un solo punto de contacto.
Incluye TODO lo que precisas para tocar',124,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\20.jpg'),
    (21,21,'21.jpg','Bateria De 5 Cuerpos + Banqueta Y Platillos','-Bombo: 22"x 16" -Tom de piso: 16"x 16" -Tom 1: 13"x 10" -Tom 2: 12"x 9-Tambor: 14"x 5,5"',326,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\21.jpg'),
    (23,23,'23.jpg','Guitarra Electrica Sx Les Paul Series Ee-3 Vintage','Body: Basswood Neck: Selected Canadian Maple Truss Rod: 2 Way Truss Rod Neck Joint: Set Neck Fingerboard: Engineered Rosewood or Rosewood',250,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\23.jpg'),
    (24,24,'24.jpg','Guitarra Electroacústica Yamaha Ncx1 Natural','La guitara electroacústica con cuerdas de nylon Yamaha NCX1 trae la artesanía tradicional a la era moderna, con una sensación familiar con grandes elementos de diseño innovadores. La NCX1 tiene una forma de cuerpo elegante, de un corte que extiende el acceso a los trastes altos, junto con una trastera de nogal de radio plano con un generoso espaciado de cuerdas de 11.8mm',180,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\24.jpg'),
    (28,28,'28.jpg','Guitarra Electrica Stratocaster 22 Trastes Con Palanca ','Selectora: 1. Humbucker, 2. Humbucker y 1er simple, 3. 1er simple, 4. 1er y 2do simple, 5. 2do simple Controles: Volumen Master, Tono 1. (Pastilla del mástil), Tono 2. (Pastilla central)',400,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\28.jpg'),
    (32,32,'32.jpg','Micrófono SF 666 condensador omnidireccional','Al ser condensador, posibilitará un resultado claro y fino. Es ideal para percusiones, guitarras, pianos, entre otros. Por su respuesta tan definida ante la voz, es el más elegido por los profesionales.',253,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\32.jpg'),
    (33,33,'33.jpg','Micrófono Fifine T730 condensador cardioide','Su patrón polar cardioide ofrece una mayor sensibilidad hacia los sonidos frontales, y así evita los ruidos provenientes de la parte posterior.',345,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\33.jpg'),
    (36,36,'36.jpg','Micrófono Fifine K730 condensador cardioide','Ideal para varias actividades. Te brindará un sonido de calidad y conseguirás la nitidez de las voces.',100,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\36.jpg'),
    (37,37,'37.jpg','Micrófono Blue Yeti condensador multipatrón blackout','La comunicación clara y poderosa es importante para todas las organizaciones. Los micrófonos de Blue te permiten capturar y transmitir con una calidad de sonido sorprendente. Blue combina audio de calidad profesional con la simplicidad plug-and-play para ofrecer un rendimiento que está a años luz de los micrófonos integrados para portátiles y cámaras.',243,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\37.jpg'),
    (38,38,'38.jpg','Micrófono Sennheiser MK 4 condensador cardioide','Con este producto lograrás que la reproducción obtenida sea lo más parecida a la original. Excelente para grabar voces debido a su sensibilidad y amplio rango de frecuencia',211,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\38.jpg'),
    (39,39,'39.jpg','Micrófono Fifine K780 condensador cardioide','Al ser condensador, posibilitará un resultado claro y fino. Es ideal para percusiones, guitarras, pianos, entre otros. Por su respuesta tan definida ante la voz, es el más elegido por los profesionales',432,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\39.jpg'),
    (40,40,'40.jpg','Micrófono Fifine K028','Diseñado para amortiguar los golpes y ruidos de manipulación. Totalmente dinámico, solo debés conectarlo y empezar a grabar.',333,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\40.jpg');




INSERT INTO SongsBD VALUES
    (36,1,'36.jpg','1968',11,'Rock, con influencias de Vernon Reid/Living Colour','TrackTribe',NULL,'kNYx2C995fc','1968 - TrackTribe.mp3','https://youtu.be/kNYx2C995fc','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\1968 - TrackTribe.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\36.jpg'),
    (28,2,'28.jpg','American Idle ',3,'HardRock clasico.','Robotanists',NULL,'P6MmUUzL-LI','American Idle - RKVC.mp3','https://youtu.be/P6MmUUzL-LI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\American Idle - RKVC.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\28.jpg'),
    (4,3,'04.jpg','Anywhen You Say ',12,'Sonidos de la dimension paralela, en una cancion lenta','Cheel',NULL,'GZDXEfy05vM','Anywhen You Say - Cheel.mp3','https://youtu.be/GZDXEfy05vM','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Anywhen You Say - Cheel.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\04.jpg'),
    (12,4,'12.jpg','Awake ',8,'Bella balada que recuerda el vaiven de las olas del mar','Emmit','Fenn','vEMR-d4VP_U','Awake - Emmit Fenn.mp3','https://youtu.be/vEMR-d4VP_U','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Awake - Emmit Fenn.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\12.jpg'),
    (39,5,'39.jpg','Beach Walk ',16,'Bass Goove y piano marcando la melodia','Hallmarc',NULL,'xmrsl0gUabo','Beach Walk - Unicorn Heads.mp3','https://youtu.be/xmrsl0gUabo','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Beach Walk - Unicorn Heads.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\39.jpg'),
    (28,6,'28.jpg','Burlesque Heartache ',1,'Potente riff de guitarra con piano marcando el ritmo','Robotanists',NULL,'yp4F34m3d7Y','Burlesque Heartache - RKVC.mp3','https://youtu.be/yp4F34m3d7Y','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Burlesque Heartache - RKVC.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\28.jpg'),
    (19,7,'19.jpg','Carried ',6,'Soul lento y relajante que te hara viajar al plano astral','Lauren','Duski','PNDZyA9yvYs','Carried - Lauren Duski.mp3','https://youtu.be/PNDZyA9yvYs','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Carried - Lauren Duski.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\19.jpg'),
    (9,8,'09.jpg','Cattle ',5,'Slow melody con sonidos de piano ambientando','Delicate','Steve','PwjyPFdifkk','Cattle - Delicate Steve.mp3','https://youtu.be/PwjyPFdifkk','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Cattle - Delicate Steve.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\09.jpg'),
    (3,9,'03.jpg','Caverns ',7,'Cancion lenta y motivacional, perfecta para ambientar comerciales','Bad','Snacks','o582JD5OoyU','Caverns - Bad Snacks.mp3','https://youtu.be/o582JD5OoyU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Caverns - Bad Snacks.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\03.jpg'),
    (1,10,'01.jpg','Cocktail Hour ',8,'Un piano en el que suenan acordes de jazz','Aaron','Kenny','dMHs6rjAgI8','Cocktail Hour - Aaron Kenny.mp3','https://youtu.be/dMHs6rjAgI8','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Cocktail Hour - Aaron Kenny.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\01.jpg'),
    (36,11,'36.jpg','Come Get With Us ',9,'Rock con toques de soul','TrackTribe',NULL,'L1d4h2180mo','Come Get With Us - TrackTribe.mp3','https://youtu.be/L1d4h2180mo','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Come Get With Us - TrackTribe.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\36.jpg'),
    (8,12,'08.jpg','Come On Out ',7,'Funk rock con un increible groove de bateria','Timothy','Hansen','3rXuuqcz-ck','Come On Out - Dan Lebowitz.mp3','https://youtu.be/3rXuuqcz-ck','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Come On Out - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (17,13,'17.jpg','Concrete ',5,'Indie Pop con sintetizadores. Energizante','JHS','Pedals','eb2WikNu_BA','Concrete - JHS Pedals.mp3','https://youtu.be/eb2WikNu_BA','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Concrete - JHS Pedals.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\17.jpg'),
    (35,14,'35.jpg','Cottonmouth Strut ',7,'Melodia especial para series de misterio','Chloe','Morondo','WT2-HXnGEDk','Cottonmouth Strut - The Whole Other.mp3','https://youtu.be/WT2-HXnGEDk','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Cottonmouth Strut - The Whole Other.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\35.jpg'),
    (9,15,'09.jpg','County Lines ',7,'Balada suave con redoblante marcante','Delicate','Steve','p33Trpj3nA4','County Lines - Delicate Steve.mp3','https://youtu.be/p33Trpj3nA4','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\County Lines - Delicate Steve.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\09.jpg'),
    (9,16,'09.jpg','Crops ',7,'Slide de guitarra electrica para marcar esta linda balada','Delicate','Steve','KbWS8mZJNGU','Crops - Delicate Steve.mp3','https://youtu.be/KbWS8mZJNGU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Crops - Delicate Steve.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\09.jpg'),
    (37,17,'37.jpg','Crush ',10,'Rock progresivo, Fusion experimental','Trevor','Garrod','jdTnBGemqZo','Crush - Trevor Garrod.mp3','https://youtu.be/jdTnBGemqZo','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Crush - Trevor Garrod.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\37.jpg'),
    (40,18,'40.jpg','Deep State ',10,'Rock industrial, influencias Depeche Mode','Vans','in Japan','oooSZHP3upk','Deep State - Vans in Japan.mp3','https://youtu.be/oooSZHP3upk','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Deep State - Vans in Japan.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\40.jpg'),
    (40,19,'40.jpg','Desert Brawl ',9,'Rock industrial, influencias Prodigy. Especial para videojuegos','Vans','in Japan','W--AstqvU30','Desert Brawl - Vans in Japan.mp3','https://youtu.be/W--AstqvU30','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Desert Brawl - Vans in Japan.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\40.jpg'),
    (25,20,'25.jpg','Disco Knights ',9,'El groove de la musica disco esta aquí. Escuchalo hasta el final','Quincas','Moreira','MDYIDMNipEY','Disco Knights - Quincas Moreira.mp3','https://youtu.be/MDYIDMNipEY','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Disco Knights - Quincas Moreira.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\25.jpg'),
    (41,21,'41.jpg','Dive Down ',5,'Motivacional. Escuchalo y llenara tu dia de alegria','Parks','Square','QwwtcMulGq4','Dive Down - VYEN.mp3','https://youtu.be/QwwtcMulGq4','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Dive Down - VYEN.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\41.jpg'),
    (8,22,'08.jpg','Don''t Ya Bite Now ',7,'Guitarra electrica en el frente, manteniendo las armonias y sin distorsiones','Timothy','Hansen','puYtMtXwmHI','Don''t Ya Bite Now - Dan Lebowitz.mp3','https://youtu.be/puYtMtXwmHI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Don''t Ya Bite Now - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (26,23,'26.jpg','Down Time In My Soul ',9,'Soul music en una caminata por el parque','RAGE',NULL,'p4OOL6P_ND4','Down Time In My Soul - RAGE.mp3','https://youtu.be/p4OOL6P_ND4','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Down Time In My Soul - RAGE.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\26.jpg'),
    (30,24,'30.jpg','Earth Bound ',4,'Reggae sintetizado. Te llevara a la playa instantaneamente','Kid','Head','zbEXXszusjs','Earth Bound - Slynk.mp3','https://youtu.be/zbEXXszusjs','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Earth Bound - Slynk.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\30.jpg'),
    (16,25,'16.jpg','Emergency On Level 3 ',7,'HardRock donde los protagonistas son sintetizadores y guitarras distorsionadas','Jeremy','Korpas','LQXFrZZKl6k','Emergency On Level 3 - Jeremy Korpas.mp3','https://youtu.be/LQXFrZZKl6k','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Emergency On Level 3 - Jeremy Korpas.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\16.jpg'),
    (8,26,'08.jpg','Everything You Wanted ',9,'Folk melody para ambientaciones','Timothy','Hansen','G5VSU0kbehg','Everything You Wanted - Dan Lebowitz.mp3','https://youtu.be/G5VSU0kbehg','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Everything You Wanted - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (34,27,'34.jpg','Fanta Mankane ',1,'Reminicencias de la musica africana','Dave','Fields','GGSzSjIIsHU','Fanta Mankane - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','https://youtu.be/GGSzSjIIsHU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Fanta Mankane - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\34.jpg'),
    (16,28,'16.jpg','Finding Synergy ',10,'Synthpop, ideal para musicalizar videojuegos','Jeremy','Korpas','FYC37xj7lZ4','Finding Synergy - Jeremy Korpas.mp3','https://youtu.be/FYC37xj7lZ4','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Finding Synergy - Jeremy Korpas.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\16.jpg'),
    (8,29,'08.jpg','Freedom_ ',3,'Balada lenta buscando los sentimientos nostalgicos que todos llevamos dentro','Timothy','Hansen','kOKAujY8SsE','Freedom_ - Dan Lebowitz.mp3','https://youtu.be/kOKAujY8SsE','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Freedom_ - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (14,30,'14.jpg','General One ',4,'Pop Reggae para escuchar camino a la playa','Aillike','Leddy','xozSHF9ki48','General One - Freedom Trail Studio.mp3','https://youtu.be/xozSHF9ki48','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\General One - Freedom Trail Studio.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\14.jpg'),
    (8,31,'08.jpg','Get Yer Glow ',1,'Funk rock con toques de una jazz guitar al frente','Timothy','Hansen','BFjzpvWMQ2o','Get Yer Glow - Dan Lebowitz.mp3','https://youtu.be/BFjzpvWMQ2o','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Get Yer Glow - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (35,32,'35.jpg','Glitchin’ a Ride ',5,'Melancolia y relax total','Chloe','Morondo','Iz7e6DY1_CA','Glitchin’ a Ride - The Whole Other.mp3','https://youtu.be/Iz7e6DY1_CA','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Glitchin’ a Ride - The Whole Other.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\35.jpg'),
    (36,33,'36.jpg','Greaser ',6,'Rock and roll del clasico para bailar','TrackTribe',NULL,'sAE621VPLTU','Greaser - TrackTribe.mp3','https://youtu.be/sAE621VPLTU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Greaser - TrackTribe.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\36.jpg'),
    (40,34,'40.jpg','Grey Flannel ',2,'Synth Rock, bateria sintetizadores y guitarra distorsionada al mango','Vans','in Japan','pv8czz-lfo8','Grey Flannel - Vans in Japan.mp3','https://youtu.be/pv8czz-lfo8','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Grey Flannel - Vans in Japan.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\40.jpg'),
    (36,35,'36.jpg','Hedge Your Bets ',6,'Jazz music para ambientar coctails','TrackTribe',NULL,'LWIVnWzzidQ','Hedge Your Bets - TrackTribe.mp3','https://youtu.be/LWIVnWzzidQ','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Hedge Your Bets - TrackTribe.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\36.jpg'),
    (21,36,'21.jpg','Ice Kenkey Beat ',6,'Balada Synthpop para el after hour. Cool','Glass','Animals','mx5OV7ly8MY','Ice Kenkey Beat - Nana Kwabena.mp3','https://youtu.be/mx5OV7ly8MY','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Ice Kenkey Beat - Nana Kwabena.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\21.jpg'),
    (7,37,'07.jpg','Infiltration Device ',4,'Progresiva. Inspiracion y King Crimsom','Jamelle','Monae','9VzNXANC7DE','Infiltration Device - Craig MacArthur.mp3','https://youtu.be/9VzNXANC7DE','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Infiltration Device - Craig MacArthur.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\07.jpg'),
    (14,38,'14.jpg','Island Woke ',9,'Reggae interpretado con piano y organo','Aillike','Leddy','8ddmRsH_2d0','Island Woke - Freedom Trail Studio.mp3','https://youtu.be/8ddmRsH_2d0','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Island Woke - Freedom Trail Studio.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\14.jpg'),
    (11,39,'11.jpg','Karma Cat ',2,'Inspirational music, para los momentos de relax y meditacion','Outside In',NULL,'WkyHCxsPi0Y','Karma Cat - Dyalla.mp3','https://youtu.be/WkyHCxsPi0Y','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Karma Cat - Dyalla.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\11.jpg'),
    (18,41,'18.jpg','King Porter Stomp ',2,'Jazz interpretado en piano solo','Joel','Cummins','xZ3CWXH-p48','King Porter Stomp - Joel Cummins.mp3','https://youtu.be/xZ3CWXH-p48','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\King Porter Stomp - Joel Cummins.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\18.jpg'),
    (14,42,'14.jpg','Kraya ',6,'Reggae roots','Aillike','Leddy','Yk-kFJOoBzk','Kraya - Freedom Trail Studio.mp3','https://youtu.be/Yk-kFJOoBzk','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Kraya - Freedom Trail Studio.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\14.jpg'),
    (34,43,'34.jpg','Kuku ',3,'Reminicencias de la musica africana percusiva','Dave','Fields','FjIS38EIKCY','Kuku - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','https://youtu.be/FjIS38EIKCY','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Kuku - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\34.jpg'),
    (4,44,'04.jpg','Kurt ',7,'Electronica con riffs de guitarra y med tempo','Cheel',NULL,'Akj5pZpMl0E','Kurt - Cheel.mp3','https://youtu.be/Akj5pZpMl0E','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Kurt - Cheel.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\04.jpg'),
    (40,45,'40.jpg','Late Night Train ',8,'Pop sintetizado, con aires a Smashing Pumpkings','Vans','in Japan','t8o07bICVjc','Late Night Train - Vans in Japan.mp3','https://youtu.be/t8o07bICVjc','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Late Night Train - Vans in Japan.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\40.jpg'),
    (38,46,'38.jpg','Leave It Alone ',7,'Melodia con toques de jazz sintetizado para la hora del te','Back 2 zero',NULL,'zwYcrTizgXs','Leave It Alone - Underbelly.mp3','https://youtu.be/zwYcrTizgXs','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Leave It Alone - Underbelly.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\38.jpg'),
    (33,47,'33.jpg','Letter To Natalie ',1,'Melancolia y relax total','Roosevelt','Sea','foHF_xOvCy0','Letter To Natalie - The Great North Sound Society.mp3','https://youtu.be/foHF_xOvCy0','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Letter To Natalie - The Great North Sound Society.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\33.jpg'),
    (39,48,'39.jpg','Light Expanse ',8,'Country sintetizado y moderno','Hallmarc',NULL,'nUVsJCNAEoE','Light Expanse - Unicorn Heads.mp3','https://youtu.be/nUVsJCNAEoE','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Light Expanse - Unicorn Heads.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\39.jpg'),
    (6,49,'06.jpg','Lilac Skies ',4,'Pop music, con influencias de Depeche Mode y Coldplay. Motivacional','Corbyn','Kites','pOZ6u4VupYU','Lilac Skies - Corbyn Kites.mp3','https://youtu.be/pOZ6u4VupYU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Lilac Skies - Corbyn Kites.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\06.jpg'),
    (17,50,'17.jpg','Listen to the Radio ',4,'Melodia pop marcada por guitarras reberveradas y sintetizadores','JHS','Pedals','AkCi49gL59o','Listen to the Radio - JHS Pedals.mp3','https://youtu.be/AkCi49gL59o','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Listen to the Radio - JHS Pedals.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\17.jpg'),
    (24,51,'24.jpg','Make Love Not War ',3,'Reggae music con tradicion','Patiño',NULL,'PqiWdtTUn14','Make Love Not War - Patiño.mp3','https://youtu.be/PqiWdtTUn14','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Make Love Not War - Patiño.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\24.jpg'),
    (16,52,'16.jpg','Manic. No Depression. ',2,'HardRock para revolear la cabeza. Guitarras y solos que te haran vibrar','Jeremy','Korpas','qcCrq0UYymk','Manic. No Depression. - Jeremy Korpas.mp3','https://youtu.be/qcCrq0UYymk','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Manic. No Depression. - Jeremy Korpas.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\16.jpg'),
    (20,53,'20.jpg','Middle Age Blues ',9,'Classic blues del Mississipi','Travis','Scott','pAx4Yf3ntOE','Middle Age Blues - Mini Vandals.mp3','https://youtu.be/pAx4Yf3ntOE','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Middle Age Blues - Mini Vandals.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\20.jpg'),
    (39,54,'39.jpg','Modern Situations ',5,'Tributo a The doors (solo le falta Morrison)','Hallmarc',NULL,'okJd5s9h_rM','Modern Situations - Unicorn Heads.mp3','https://youtu.be/okJd5s9h_rM','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Modern Situations - Unicorn Heads.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\39.jpg'),
    (34,55,'34.jpg','Momo Do ',4,'Reminicencias de la musica africana','Dave','Fields','EaAjW1QNibM','Momo Do - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','https://youtu.be/EaAjW1QNibM','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Momo Do - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\34.jpg'),
    (22,56,'22.jpg','Moon Rock ',4,'Fusion melody chorus guitar, synth y bateria marcante','Nathan','Moore','5fI8RPjCIKo','Moon Rock - Nathan Moore.mp3','https://youtu.be/5fI8RPjCIKo','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Moon Rock - Nathan Moore.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\22.jpg'),
    (36,57,'36.jpg','Motorbike ',4,'Country music, recordando el Oeste','TrackTribe',NULL,'l97ZNvPHmrU','Motorbike - TrackTribe.mp3','https://youtu.be/l97ZNvPHmrU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Motorbike - TrackTribe.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\36.jpg'),
    (8,58,'08.jpg','Movin'' Up ',7,'Funk del clasico. Sino moves la cabeza es que estas muerto….','Timothy','Hansen','XNeTns45wm8','Movin'' Up - Dan Lebowitz.mp3','https://youtu.be/XNeTns45wm8','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Movin'' Up - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (8,59,'08.jpg','Never You Mind ',8,'Base de rock, sobre una guitarra semi distorsionada estilo funky','Timothy','Hansen','dV0eWrRGq6s','Never You Mind - Dan Lebowitz.mp3','https://youtu.be/dV0eWrRGq6s','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Never You Mind - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (34,60,'34.jpg','Ngoni ',7,'Reggae percursivo y experimental con flauta traversa','Dave','Fields','lj0jm9kDknI','Ngoni - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','https://youtu.be/lj0jm9kDknI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Ngoni - The Mini Vandals featuring Mamadou Koita and Lasso.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\34.jpg'),
    (32,61,'32.jpg','Not Impossible ',1,'Toms de bateria en un colchon sonoro de guitara y teclados','Air','Review','St62ZePnsQM','Not Impossible - The 126ers.mp3','https://youtu.be/St62ZePnsQM','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Not Impossible - The 126ers.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\32.jpg'),
    (5,62,'05.jpg','Old Blue ',1,'Blues con influencias de country music y old style','Chris','Haugen','KO27HopJAOk','Old Blue - Chris Haugen.mp3','https://youtu.be/KO27HopJAOk','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Old Blue - Chris Haugen.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\05.jpg'),
    (8,63,'08.jpg','Overdrive Ride ',2,'Rock and roll, baby yes. Perfecto para ambientar publicidades','Timothy','Hansen','_YJO9xrJhPg','Overdrive Ride - Dan Lebowitz.mp3','https://youtu.be/_YJO9xrJhPg','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Overdrive Ride - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (16,64,'16.jpg','Patterns Of Sadness ',2,'Rock experimental','Jeremy','Korpas','NjIGvYyhg-M','Patterns Of Sadness - Jeremy Korpas.mp3','https://youtu.be/NjIGvYyhg-M','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Patterns Of Sadness - Jeremy Korpas.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\16.jpg'),
    (13,65,'13.jpg','Peacefully ',9,'Jazz para ver la lluvia caer desde la ventana','E''s','Jammy Jams','QtZrec_R1bU','Peacefully - E''s Jammy Jams.mp3','https://youtu.be/QtZrec_R1bU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Peacefully - E''s Jammy Jams.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\13.jpg'),
    (7,66,'07.jpg','Potato Deal ',1,'Rock progresivo con influencias de Creedence y otras bandas clasicas','Jamelle','Monae','5l5Fybp712I','Potato Deal - Craig MacArthur.mp3','https://youtu.be/5l5Fybp712I','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Potato Deal - Craig MacArthur.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\07.jpg'),
    (14,67,'14.jpg','Remember September ',2,'Melodia reggae con arpegio y solo de guitarra electrica','Aillike','Leddy','riG3R9KfKqE','Remember September - Freedom Trail Studio.mp3','https://youtu.be/riG3R9KfKqE','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Remember September - Freedom Trail Studio.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\14.jpg'),
    (39,68,'39.jpg','Rolling Heads ',1,'Rock del clasico. Tributo a Stevie Ray','Hallmarc',NULL,'4soZwSEsD4w','Rolling Heads - Unicorn Heads.mp3','https://youtu.be/4soZwSEsD4w','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Rolling Heads - Unicorn Heads.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\39.jpg'),
    (9,69,'09.jpg','Rooster ',3,'Las teclas son las protagonistas. Balada irregular a contratiempo','Delicate','Steve','TkPGZL87nOI','Rooster - Delicate Steve.mp3','https://youtu.be/TkPGZL87nOI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Rooster - Delicate Steve.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\09.jpg'),
    (9,70,'09.jpg','Sailing ',5,'Musica suave para la hora de ir a domir','Delicate','Steve','SwstFJ8kzkI','Sailing - Delicate Steve.mp3','https://youtu.be/SwstFJ8kzkI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Sailing - Delicate Steve.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\09.jpg'),
    (9,71,'09.jpg','Seasons ',5,'Balada con sonidos espaciales y un toque de blues','Delicate','Steve','8OGBfA6O3lY','Seasons - Delicate Steve.mp3','https://youtu.be/8OGBfA6O3lY','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Seasons - Delicate Steve.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\09.jpg'),
    (32,72,'32.jpg','See You On The Otherside ',3,'Pop music motivacional','Air','Review','Lcv0TAF0wnA','See You On The Otherside - The 126ers.mp3','https://youtu.be/Lcv0TAF0wnA','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\See You On The Otherside - The 126ers.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\32.jpg'),
    (21,73,'21.jpg','She No Dull Beat ',5,'Reggae sintetico','Glass','Animals','7bflzjLFZqg','She No Dull Beat - Nana Kwabena.mp3','https://youtu.be/7bflzjLFZqg','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\She No Dull Beat - Nana Kwabena.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\21.jpg'),
    (4,74,'04.jpg','Soft Feeling ',10,'Sonidos celestiales en un low tempo','Cheel',NULL,'sn7OY_FP5Og','Soft Feeling - Cheel.mp3','https://youtu.be/sn7OY_FP5Og','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Soft Feeling - Cheel.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\04.jpg'),
    (40,75,'40.jpg','Sonic Pogo ',10,'Melodia para videojuegos','Vans','in Japan','Li2Pr_W65ws','Sonic Pogo - Vans in Japan.mp3','https://youtu.be/Li2Pr_W65ws','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Sonic Pogo - Vans in Japan.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\40.jpg'),
    (33,76,'33.jpg','South Street Strut ',2,'Melodia cautivante para publicidades','Roosevelt','Sea','AaoFCOtKRFY','South Street Strut - The Great North Sound Society.mp3','https://youtu.be/AaoFCOtKRFY','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\South Street Strut - The Great North Sound Society.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\33.jpg'),
    (10,77,'10.jpg','Spy vs Spy ',4,'Rock a gogo. La autentica marcha de los espias','Replacements',NULL,'Bpq7qQJIMw4','Spy vs Spy - DJ Williams.mp3','https://youtu.be/Bpq7qQJIMw4','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Spy vs Spy - DJ Williams.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\10.jpg'),
    (6,78,'06.jpg','Staycation ',10,'Soul music and cool ambient','Corbyn','Kites','3YeZ4T1hkKM','Staycation - Corbyn Kites.mp3','https://youtu.be/3YeZ4T1hkKM','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Staycation - Corbyn Kites.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\06.jpg'),
    (24,79,'24.jpg','Stoner Things ',8,'Intro para documentales o noticieros','Patiño',NULL,'yurWoLO2X5c','Stoner Things - Patiño.mp3','https://youtu.be/yurWoLO2X5c','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Stoner Things - Patiño.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\24.jpg'),
    (17,80,'17.jpg','Summer ',1,'Pop melodioso y melancolico con influencias de Smashing Pumpkings','JHS','Pedals','ACYCwBoO6mI','Summer - JHS Pedals.mp3','https://youtu.be/ACYCwBoO6mI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Summer - JHS Pedals.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\17.jpg'),
    (9,81,'09.jpg','Sunshine ',2,'Las teclas son las protagonistas. Balada irregular a contratiempo','Delicate','Steve','wuSUg-eI5YA','Sunshine - Delicate Steve.mp3','https://youtu.be/wuSUg-eI5YA','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Sunshine - Delicate Steve.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\09.jpg'),
    (16,82,'16.jpg','Superfuzz Grind ',4,'Rock potente, con predominancia de guitarras y sintetizador','Jeremy','Korpas','tZ7hhkfLpt4','Superfuzz Grind - Jeremy Korpas.mp3','https://youtu.be/tZ7hhkfLpt4','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Superfuzz Grind - Jeremy Korpas.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\16.jpg'),
    (5,83,'05.jpg','Swampland ',8,'Rithm and blues clasico, con un leve flavour a aquel viaje por el oeste americano','Chris','Haugen','SANccBFu_b4','Swampland - Chris Haugen.mp3','https://youtu.be/SANccBFu_b4','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Swampland - Chris Haugen.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\05.jpg'),
    (8,84,'08.jpg','Sweet Release ',1,'Balada nostalgica con guitarra acustica y slide','Timothy','Hansen','ARt3H26Ddms','Sweet Release - Dan Lebowitz.mp3','https://youtu.be/ARt3H26Ddms','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Sweet Release - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (42,85,'42.jpg','Sweet Relief ',8,'Hermosa balada para momentos especiales','Zachariah','Hickman','bHYra7xqVpA','Sweet Relief - Zachariah Hickman.mp3','https://youtu.be/bHYra7xqVpA','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Sweet Relief - Zachariah Hickman.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\42.jpg'),
    (29,86,'29.jpg','Take it Slow ',4,'Funk sintetizado con efectos polimorficos','SefChol',NULL,'_i1OLC7W3Ns','Take it Slow - SefChol.mp3','https://youtu.be/_i1OLC7W3Ns','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Take it Slow - SefChol.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\29.jpg'),
    (23,87,'23.jpg','Tea Time ',5,'Bass and drum en una atmosfera soul','Ofshane',NULL,'F5BpJ46BYYI','Tea Time - Ofshane.mp3','https://youtu.be/F5BpJ46BYYI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Tea Time - Ofshane.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\23.jpg'),
    (28,89,'28.jpg','That One Bar Scene ',1,'Base de rock, sobre una guitarra semi distorsionada','Robotanists',NULL,'Qz4mWKSzLcI','That One Bar Scene - RKVC.mp3','https://youtu.be/Qz4mWKSzLcI','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\That One Bar Scene - RKVC.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\28.jpg'),
    (30,90,'30.jpg','The Jam ',1,'La escencia del funk, solo de saxo y el groove del bajo como protagonista','Kid','Head','kUxpApYRXzU','The Jam - Slynk & Mr Stabalina.mp3','https://youtu.be/kUxpApYRXzU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\The Jam - Slynk & Mr Stabalina.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\30.jpg'),
    (7,91,'07.jpg','The Old RV ',9,'Soul music, Marvin Gaye Inspiration','Jamelle','Monae','MzEgUqXiaqc','The Old RV - Craig MacArthur.mp3','https://youtu.be/MzEgUqXiaqc','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\The Old RV - Craig MacArthur.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\07.jpg'),
    (2,92,'02.jpg','The Truth ',4,'Soul music para relajarse','Nate','Parrish','5DzpaGtCcKE','The Truth - Anno Domini Beats.mp3','https://youtu.be/5DzpaGtCcKE','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\The Truth - Anno Domini Beats.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\02.jpg'),
    (36,93,'36.jpg','Thumbs On Ones ',8,'Electronica Fusion','TrackTribe',NULL,'HU98xmWK5DU','Thumbs On Ones - TrackTribe.mp3','https://youtu.be/HU98xmWK5DU','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Thumbs On Ones - TrackTribe.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\36.jpg'),
    (14,94,'14.jpg','Tin Spirit ',4,'Reggae roots con organo','Aillike','Leddy','O1HuqmLvsUA','Tin Spirit - Freedom Trail Studio.mp3','https://youtu.be/O1HuqmLvsUA','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Tin Spirit - Freedom Trail Studio.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\14.jpg'),
    (15,95,'15.jpg','Toddler Band ',3,'Marcha de base piano y organo (atmosfera)','Godmode',NULL,'XBm2F1dyp_U','Toddler Band - Godmode.mp3','https://youtu.be/XBm2F1dyp_U','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Toddler Band - Godmode.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\15.jpg'),
    (8,96,'08.jpg','Trimmed & Taught ',3,'Riff de polka fusionado con base de pop','Timothy','Hansen','NQGlr8PmdYg','Trimmed & Taught - Dan Lebowitz.mp3','https://youtu.be/NQGlr8PmdYg','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Trimmed & Taught - Dan Lebowitz.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\08.jpg'),
    (31,97,'31.jpg','Tubby ',2,'Harmonica que acompana de fondo una linda melodia','Steve','Adams','19yP-DoB69g','Tubby - Steve Adams.mp3','https://youtu.be/19yP-DoB69g','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Tubby - Steve Adams.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\31.jpg'),
    (29,98,'29.jpg','Two Sides ',3,'Reggae sintetizado full efectos','SefChol',NULL,'KzuXkIh0cVA','Two Sides - SefChol.mp3','https://youtu.be/KzuXkIh0cVA','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Two Sides - SefChol.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\29.jpg'),
    (32,99,'32.jpg','Warships ',1,'Fusion melody chorus guitar, synth y bateria marcante','Air','Review','WG6S1BerpJw','Warships - The 126ers.mp3','https://youtu.be/WG6S1BerpJw','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\Warships - The 126ers.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\32.jpg'),
    (27,100,'27.jpg','We Ride! ',1,'Rock and roll del clasico para bailar','Reed','Mathis','Cmzuaozboms','We Ride! - Reed Mathis.mp3','https://youtu.be/Cmzuaozboms','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\MusicFiles\\We Ride! - Reed Mathis.mp3','C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\MusicFilesCoverImg\\resized\\27.jpg');

