CREATE TABLE IF NOT EXISTS InstrumentsDB (
    `id` INT,
    `InstrumId` INT,
    `img` VARCHAR(6) CHARACTER SET utf8,
    `titulo` VARCHAR(60) CHARACTER SET utf8,
    `descripcion` VARCHAR(418) CHARACTER SET utf8,
    `precio` INT,
    `pathAbsolute_img_native` VARCHAR(108) CHARACTER SET utf8
);
INSERT INTO InstrumentsDB VALUES
    (1,1,'01.jpg','Bajo Electrico Acustico Femmto Precision','CARACTERISTICAS - Formato de guitarra simil Jazz Bass, para diestros, pasivo - Madera cuerpo: Aliso - Madera mástil: Arce - Diapasón: Palisandro - Clavijas forma trébol, 4L, de fundición cromadas - Cuerdas de metal - microfono bobina partida (split coil, tipo Precision Bass) - 2 perillas (volumen y tono) - 21 trastes - Pick guard
- Salida: Jack plug 6.5mm',42,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\01.jpg'),
    (2,2,'02.jpg','Bajo Electrico Fender Jaguar Bass 4 Cuerdas','Producto: Bajo Electrico
Marca: Fender
Modelo: Jaguar Bass Caracteristicas: Bajo Electrico Fender Jaguar Bass 4 Cuerdas Perfecto Estado.',333,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\02.jpg'),
    (3,3,'03.jpg','Bajo Electrico 4 Cuedras Con Ampli Y Afinador','Bajo usado en buen estado no se la marca',36,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\03.jpg'),
    (4,4,'04.jpg','Bajo Eléctrico Guild - Década Del 90 Impecable - Gran Sonido','Como nuevo. Hecho en Argentina. Década de 1980 a 1990. Impecable',140,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\04.jpg'),
    (5,5,'05.jpg','Bajo Electrico Texas','Bajo eléctrico de 4 cuerdas tipo Ibanez, de circuito Activo. Dos mics unos tipo jazz bass y el otro precision bass. Dos perillas de tonos, dos perillas de volumen. Color Tobacoo Burst. Solo de poco uso doméstico. Buen sonido. Calibrado con cuerdas nuevas Martin Blust de .40. Se entrega con funda de bajo acolchonada y una pua rigida. Zona Ezeiza para probarlo o entrega en todo el Conurbano Bonaerense previo acuerdo.',134,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\05.jpg'),
    (6,6,'06.jpg','Bajo Electrico Tipo Fender Tyler','Exelente bajo tipo fender tyler vintage series jazz bass, exelente estado se lo compre a la persona q lo compro nuevo y no lo uso yo lo use muy copo, lindo sonido con funda',37,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\06.jpg'),
    (7,7,'07.jpg','Bajo Eléctrico Corvette Rock Bass By Warwick 5 Cuerdas Local','SE RETIRA POR EL CENTRO DE LOMAS DE ZAMORA O ENVIO POR MERCADO ENVIO. LOCAL A LA CALLE',27,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\07.jpg'),
    (8,8,'08.jpg','Bajo Electrico Ibanez Gio Gsr 200','Poco uso, solo para maquetear en casa y algún ensayo.
Detalles que pueden verse en las fotos.
La tapa de la batería engancha de un solo lado y del otro lo sostengo con cinta, no afecta al uso ni se cae la batería.
Anda 10 puntos pero busco algún bajo PASIVO ya que soy guitarrista y me resulta más practico para maquetear, no preciso la ganancia de un bajo activo.',330,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\08.jpg'),
    (9,9,'09.jpg','Bajo Eléctrico Dean Hillsboro Blue Activo Jazz Bass','Los bajos de Dean Hillsboro tienen un aspecto retro y un cabezal clásico. Diseñados para jazz, funk y rock, estos instrumentos son ideales para músicos con poco presupuesto que buscan algo un poco diferente.',181,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\09.jpg'),
    (10,10,'10.jpg','Bajo Electrico 5 Cuerdas Ibanez Btb 775 Pb/indonesia','Ibanez BTB five string with Poplar Burl top, Maple neck and Mahogany body.  MK-2 Pickups . 35" scale. 1.85" at nut.  Neck through. Has been played but still in mint condition. Includes cool Hanewinckel padded Gigbag.  Really nice playing fiver with typical Ibanez quality.   Always wanted to try one of these and it didn''t disappoint but I just got an Alembic five string so I can let this go. Ver detalle de la foto.',329,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\10.jpg'),
    (11,11,'11.jpg','Bateria Acústica 5 Cpos Platos Fierros','BATERIA STAR 5 CUERPOS CON FIERROS Y SIN PALILLOS -Tom 12" -Tom 13" -Redoblante 14" -Chancha 16" -Soportes y pedal para Hihat -Soporte recto para Crash.',151,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\11.jpg'),
    (12,12,'12.jpg','Bateria De 5 Cuerpos + Banqueta Y Platillos Natal Dna Gris','La batería NATAL DNA viene completa, con hardware, platillos, pedal para el bombo, butaca e incluso baquetas; todo lo que necesitas para tocar la batería directamente de la caja.',331,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\12.jpg'),
    (13,13,'13.jpg','Bateria Pearl 5 C Export Exx725 22/10/12/16/14x5 Blanco Mate','BATERÍA PEARL Export - 5 Cuerpos - B22"x18 | TT10"x7 | TT12"x8 | TF16"x16 | R14"x5 - Poplar-Mahogany- Jet Black - Sin Fierros',91,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\13.jpg'),
    (14,14,'14.jpg','Batería Acústica Taurus Jazz Maple 4 Cpos Tambo 14 Bombo 18','Batería 4 cuerpos Maple Tom tom 12" x 10" Tom de pie 14" x 16" Bombo 18" x 18" Tambor 14 Rims Flotantes Bombo con 8 torres AROS DE MADERA
Tom holder t/YAMAHA Patas telescópicas Fierros Dobles Soporte Recto Platillo pata doble Soporte HH con regulación pata doble Pedal de bombo cadena doble plataforma de acero
Soporte de redoblante pata doble',14,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\14.jpg'),
    (16,16,'16.jpg','Bateria Mapex Mars Fusion Bombo De 20 Bloodwood Cuotas','Bombo 20"x16" sin soporte para Tom. Tom Tom 10"x07" y 12"x08" Tom Base 14"x12" Caja 14"x6,5 Mars Incluye Soporte doble de tom TH676 No incluye herrajes ni platos ',265,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\16.jpg'),
    (17,17,'17.jpg','Bateria Acustica Completa 5 Cuerpos Platos Fierros','Excelente batería MAPEX PRODIGY, con acabado recubierto, los tambores están equipados con Prodigy, el nuevo modelo que utiliza un solo punto de contacto.
Incluye TODO lo que precisas para tocar',115,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\17.jpg'),
    (20,20,'20.jpg','Bateria Mapex Prodigy Completa','Excelente batería MAPEX PRODIGY, con acabado recubierto, los tambores están equipados con Prodigy, el nuevo modelo que utiliza un solo punto de contacto.
Incluye TODO lo que precisas para tocar',124,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\20.jpg'),
    (21,21,'21.jpg','Bateria De 5 Cuerpos + Banqueta Y Platillos','-Bombo: 22"x 16" -Tom de piso: 16"x 16" -Tom 1: 13"x 10" -Tom 2: 12"x 9-Tambor: 14"x 5,5"',326,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\21.jpg'),
    (23,23,'23.jpg','Guitarra Electrica Sx Les Paul Series Ee-3 Vintage','Body: Basswood Neck: Selected Canadian Maple Truss Rod: 2 Way Truss Rod Neck Joint: Set Neck Fingerboard: Engineered Rosewood or Rosewood',250,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\23.jpg'),
    (24,24,'24.jpg','Guitarra Electroacústica Yamaha Ncx1 Natural','La guitara electroacústica con cuerdas de nylon Yamaha NCX1 trae la artesanía tradicional a la era moderna, con una sensación familiar con grandes elementos de diseño innovadores. La NCX1 tiene una forma de cuerpo elegante, de un corte que extiende el acceso a los trastes altos, junto con una trastera de nogal de radio plano con un generoso espaciado de cuerdas de 11.8mm',180,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\24.jpg'),
    (28,28,'28.jpg','Guitarra Electrica Stratocaster 22 Trastes Con Palanca ','Selectora: 1. Humbucker, 2. Humbucker y 1er simple, 3. 1er simple, 4. 1er y 2do simple, 5. 2do simple Controles: Volumen Master, Tono 1. (Pastilla del mástil), Tono 2. (Pastilla central)',400,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\28.jpg'),
    (32,32,'32.jpg','Micrófono SF 666 condensador omnidireccional','Al ser condensador, posibilitará un resultado claro y fino. Es ideal para percusiones, guitarras, pianos, entre otros. Por su respuesta tan definida ante la voz, es el más elegido por los profesionales.',253,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\32.jpg'),
    (33,33,'33.jpg','Micrófono Fifine T730 condensador cardioide','Su patrón polar cardioide ofrece una mayor sensibilidad hacia los sonidos frontales, y así evita los ruidos provenientes de la parte posterior.',345,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\33.jpg'),
    (36,36,'36.jpg','Micrófono Fifine K730 condensador cardioide','Ideal para varias actividades. Te brindará un sonido de calidad y conseguirás la nitidez de las voces.',100,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\36.jpg'),
    (37,37,'37.jpg','Micrófono Blue Yeti condensador multipatrón blackout','La comunicación clara y poderosa es importante para todas las organizaciones. Los micrófonos de Blue te permiten capturar y transmitir con una calidad de sonido sorprendente. Blue combina audio de calidad profesional con la simplicidad plug-and-play para ofrecer un rendimiento que está a años luz de los micrófonos integrados para portátiles y cámaras.',243,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\37.jpg'),
    (38,38,'38.jpg','Micrófono Sennheiser MK 4 condensador cardioide','Con este producto lograrás que la reproducción obtenida sea lo más parecida a la original. Excelente para grabar voces debido a su sensibilidad y amplio rango de frecuencia',211,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\38.jpg'),
    (39,39,'39.jpg','Micrófono Fifine K780 condensador cardioide','Al ser condensador, posibilitará un resultado claro y fino. Es ideal para percusiones, guitarras, pianos, entre otros. Por su respuesta tan definida ante la voz, es el más elegido por los profesionales',432,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\39.jpg'),
    (40,40,'40.jpg','Micrófono Fifine K028','Diseñado para amortiguar los golpes y ruidos de manipulación. Totalmente dinámico, solo debés conectarlo y empezar a grabar.',333,'C:\\Users\\danin\\Downloads\\VSC-DH\\Proyecto-Integrador-DH\\public\\images\\instrumentsImg\\resizedandcropped\\40.jpg');
